name: my-app

on:
  # Запуск при пушах в основную ветку
  push:
    branches: ['main']

  # Позволяет запустить этот workflow вручную из вкладки Actions
  workflow_dispatch:

# Устанавливает разрешения GITHUB_TOKEN для развертывания на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешает одно одновременное развертывание
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Единственная работа по развертыванию
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Загрузка артефактов из папки dist
          path: './public/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2